version: "3"

services:
  nginx:
      image: nginx
      container_name: tim-nginx
      volumes:
        - ./webserver/nginx_self_ssl/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./key.pem:/root/ssl/key.pem
        - ./cert.pem:/root/ssl/cert.pem
      ports:
        - "443:443"
      depends_on:
        - telegram_bot
      restart: unless-stopped

  exchanges-data:
    image: tim/exchanges-data
    container_name: exchanges_data
    build:
      context: ~/Crypto_Bot/Crypto_bot_API/
      dockerfile: Dockerfile_exchanges
    restart: unless-stopped

  text-generator:
    image: text-generator
    container_name: text_creator
    build:
      context: ~/Crypto_Bot/Content_for_bot/
      dockerfile: Dockerfile_text
    restart: unless-stopped

  telegram_bot:
    image: tim/bot
    container_name: bot_app
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    build:
      context: .
      dockerfile: Dockerfile_bot
    depends_on:
      - text-generator
      - exchanges-data
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: tim-redis_server
    command: ["redis-server", "--save", "3600", "1000", "--loglevel", "warning", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - cache:/data
    restart: unless-stopped
    env_file:
      - .env
#  mongodb:
#    image: mongo
#    container_name: mongodb

volumes:
  cache:
    driver: local

