services:
  exchanges-data:
    image: exchanges-data
    container_name: exchanges_data
    build:
      context: /home/tim/PycharmProjects/Crypto_bot_API/
      dockerfile: dockerfile
    restart: on-failure

  text-generator:
    image: text-generator
    container_name: text_creator
    build:
      context: /home/tim/PycharmProjects/Crypto_bot_API/
      dockerfile: dockerfile
    restart: on-failure


  telegram_bot:
    image: bot
    container_name: bot_app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - text-generator
      - exchanges-data
      - redis
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis_server
    environment:
      - REDIS_PASSWORD=
    volumes:
      - '/path/to/redis-persistence:/bitnami'
    restart: on-failure


  mongodb:
    image: mongo
    container_name: mongodb
