services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 3335:80
      - 3333:443
    volumes:
      - /root/Crypto_Bot/nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/Crypto_Bot/ssl/*:/usr/nginx/

  exchanges-data:
    image: exchanges-data
    container_name: exchanges_data
    build:
      context: ~/Crypto_Bot/Crypto_bot_API/
      dockerfile: dockerfile
    restart: unless-stopped

  text-generator:
    image: text-generator
    container_name: text_creator
    build:
      context: ~/Crypto_Bot/Content_for_bot/
      dockerfile: dockerfile
    restart: unless-stopped

  telegram_bot:
    image: bot
    container_name: bot_app
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - nginx
      - text-generator
      - exchanges-data
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_server
    command: ["redis-server", "--save", "3600", "1000", "--loglevel", "warning", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - cache:/data
    restart: unless-stopped
    env_file:
      - .env
#  mongodb:
#    image: mongo
#    container_name: mongodb

volumes:
  cache:
    driver: local
