services:
  exchanges-data:
    image: exchanges-data
    container_name: exchanges_data
    build:
      context: ~/PycharmProjects/Crypto_bot_API/
      dockerfile: dockerfile
    restart: unless-stopped

  text-generator:
    image: text-generator
    container_name: text_creator
    build:
      context: ~/PycharmProjects/Content_for_bot/
      dockerfile: dockerfile
    restart: unless-stopped

  telegram_bot:
    image: bot
    container_name: bot_app
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - text-generator
      - exchanges-data
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_server
    command:
      - redis-server --save 60 100 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data
    restart: unless-stopped
#  mongodb:
#    image: mongo
#    container_name: mongodb

volumes:
  cache:
    driver: local