services:
  fastapi:
    image: fastapi
    container_name: fastapi_app
    ports:
    - "8888:8888"
    build:
      context: /home/tim/PycharmProjects/Crypto_bot_API/
      dockerfile: dockerfile

  telegram_bot:
    image: bot
    container_name: bot_app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - fastapi
      - redis

  redis:
    image: redis:latest
    container_name: redis_server
    environment:
      - REDIS_PASSWORD=
    volumes:
      - '/path/to/redis-persistence:/bitnami'
