services:
  nginx:
    build: ./webserver/nginx
    image: tim/nginx-proxy
    container_name: nginx-proxy-server
    env_file:
      - ./webserver/config.env
    volumes:
      - nginx_conf:/etc/nginx/sites
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./webserver/vhosts:/etc/nginx/vhosts
      - ./webserver/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    build: ./webserver/certbot
    image: tim/certbot
    container_name: certbot-ssl
    env_file:
      - ./webserver/config.env
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot

  cron:
    build: ./webserver/cron
    image: tim/cron
    container_name: cron-background
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

  exchanges-data:
    build:
      context: ~/Crypto_Bot/Crypto_bot_API/
      dockerfile: Dockerfile_exchanges
    image: tim/exchanges-data
    container_name: exchanges_data
    restart: unless-stopped

  text-generator:
    build:
      context: ~/Crypto_Bot/Content_for_bot/
      dockerfile: Dockerfile_text
    image: tim/text-generator
    container_name: text_creator
    restart: unless-stopped

  telegram_bot:
    build:
      context: ./src
      dockerfile: Dockerfile_bot
    image: tim/bot
    container_name: bot_app
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    depends_on:
      - text-generator
      - exchanges-data
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_server
    env_file:
      - src/.env.internal
    command: ["redis-server", "--save", "3600", "1000", "--loglevel", "warning", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - cache:/data
    restart: unless-stopped
#  mongodb:
#    image: mongo
#    container_name: mongodb

volumes:
  cache:
    driver: local
  nginx_conf:
    external: true
  letsencrypt_certs:
    external: true
  certbot_acme_challenge:
