services:
  fastapi:
    image: fastapi
    container_name: fastapi_app
    ports:
    - "8000:8000"
    build:
      context: /home/tim/PycharmProjects/Crypto_bot_API/
      dockerfile: dockerfile

  telegram_bot:
    image: bot
    container_name: bot_app
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - fastapi
